export const projects = [
  {
    title: 'Tindog Static Page',
    description: "Tindog is a fun app that provides dog lovers with the fastest, easiest way to meet other pet parents and their dog counterparts. This project is created to meet the requirements of web development boot camp in Udemy.",
      image: '/images/1.png',
      tags: ['HTML', 'CSS', 'Bootstrap'],
    source: 'https://github.com/Dxdiag14/tindog',
    visit: 'https://tindog-dxdiag14.vercel.app/',
    id: 0,
  },
  {
    title: 'Loopstudios Landing Page',
    description:"This landing page is from front-end mentor challenges. This challenge focuses mostly on HTML & CSS. There's a tiny bit of JS included for the mobile navigation toggle. I've done this project with the help of said stack.",
    image: '/images/2.png',
    tags: ['HTML', 'CSS', 'JavaScript'],
    source: 'https://github.com/Dxdiag14/Front-end-Mentor',
    visit: 'https://front-end-mentor-dxdiag14.vercel.app/',
    id: 1,
  },
  {
    title: 'Little Angry Bunny V2',
    description: "Little Angry Bunny is decentralized BEP-20token. Inspired by the little coins, LAB is a 70% community driven token with anti whale features to prevent whale dumps and protect the holders.",
      image: '/images/3.png',
      tags: ['HTML', 'CSS', 'Tailwind'],
    source: 'https://github.com/Dxdiag14/LittleAngryBunny',
    visit: 'https://littleangrybunnyv2.com/',
    id: 2,
  },
  {
    title: 'Dolla React Website - Smooth scroll',
    description: "A React website using styled components and React smooth scroll. This is a tutorial from Brian Design from youtube. This website is fully responsive and it uses React hooks and React Router.",
      image: '/images/4.png',
      tags: ['React', 'Styled Components'],
    source: 'https://github.com/Dxdiag14/dolla-website-react',
    visit: 'https://dolla-react-website.netlify.app/',
    id: 2,
  },
  {
    title: 'Lavish React Website - CSS',
    description: "A React website using React Hooks and React Router. This is a tutorial from Brian Design from youtube. This website is fully responsive and the components is reusable.",
      image: '/images/5.png',
      tags: ['React', 'CSS'],
    source: 'https://github.com/Dxdiag14/lavish-react-css',
    visit: 'https://lavish-css.netlify.app/',
    id: 2,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Develop my skills in hardware and software troubleshooting', },
  { year: 2018, text: 'Started my journey as a BSIS Student at UCC', },
  { year: 2019, text: 'Develop my skills in programming', },
  { year: 2020, text: 'Founded my interest in developing websites', },
  { year: 2021, text: 'Started to attend bootcamps and training and still learning the latest technologies in web development', },
];